name: JS Test ace

on: [push]
# on:
#   push:
#     paths:
#     - '**.js'

jobs:
  test:
    name: Test ace

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install
      run: make install

    - name: Run tests
      run: make wtr
